Repository databrickslabs/dlt-meta, pull requests merged in 2025-08, with the labels that each got.

#192 Provide UI using datbaricks lakehouse app for onboarding/deploy dlt-meta commands
  docs/content/app/_index.md
  lakehouse_app/README.md
  lakehouse_app/app.py
  lakehouse_app/app.yaml
  lakehouse_app/requirements.txt
  lakehouse_app/templates/landingPage.html
  src/cli.py
Labels: enhancement

#196 Issue 195
  .coveragerc
  .github/workflows/onpush.yml
  README.md
  demo/README.md
  docs/content/_index.md
  docs/content/additionals/integration_tests.md
  docs/content/demo/_index.md
  docs/content/faq/execution.md
  docs/content/faq/general.md
  docs/content/getting_started/dltmeta_manual.md
  integration_tests/notebooks/cloudfile_runners/validate.py
  integration_tests/notebooks/eventhub_runners/validate.py
  integration_tests/notebooks/kafka_runners/validate.py
  integration_tests/notebooks/snapshot_runners/validate.py
  labs.yml
  setup.py
  src/cli.py
  src/dataflow_pipeline.py
  src/dataflow_spec.py
  src/pipeline_writers.py
  tests/resources/onboarding_applychanges_from_snapshot.json
  tests/resources/onboarding_applychanges_from_snapshot_error.json
  tests/resources/onboarding_applychanges_from_snapshot_silver.json
  tests/resources/onboarding_v0.0.10.json
  tests/test_cli.py
  tests/test_dataflow_pipeline.py
  tests/test_dataflow_spec.py
  tests/test_install.py
  tests/test_onboard_dataflowspec.py
  tests/test_pipeline_readers.py
  tests/utils.py
Labels: enhancement

#201 - fixed pypi download stats to point pepy.tech instead of pypy stats
  README.md
Labels: bug

#203 issue 22
  demo/README.md
  demo/dabs/conf/dqe/dqe_silver_people.json
  demo/dabs/conf/onboarding_bronze_silver_people.template
  demo/dabs/conf/onboarding_silver_fanout_people.template
  demo/dabs/conf/silver_queries_people.json
  demo/dabs/notebooks/init_dlt_meta_pipeline.ipynb
  demo/dabs/resources/data/people/people.csv
  demo/dabs/resources/people_job.yml
  demo/dabs/resources/people_pipeline.yml
  demo/dabs/resources/var_people.yml
Labels: documentation
